version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: hap-nodejs
    versions:
    - 0.8.5
    - 0.9.0
    - 0.9.1
    - 0.9.2
    - 0.9.3
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: chalk
    versions:
    - 4.1.0
